/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as MyReportsRouteImport } from './routes/my-reports'
import { Route as MyRequestsRouteImport } from './routes/my-requests'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RequestDocumentRouteImport } from './routes/request-document'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminDocumentRequestsRouteImport } from './routes/admin.document-requests'
import { Route as AdminProblemReportsRouteImport } from './routes/admin.problem-reports'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminResidentFeedbackRouteImport } from './routes/admin.resident-feedback'
import { Route as AdminResidentVerificationRouteImport } from './routes/admin.resident-verification'
import { Route as AdminTransactionHistoryRouteImport } from './routes/admin.transaction-history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReportsRoute = MyReportsRouteImport.update({
  id: '/my-reports',
  path: '/my-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRequestsRoute = MyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestDocumentRoute = RequestDocumentRouteImport.update({
  id: '/request-document',
  path: '/request-document',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentRequestsRoute = AdminDocumentRequestsRouteImport.update({
  id: '/document-requests',
  path: '/document-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProblemReportsRoute = AdminProblemReportsRouteImport.update({
  id: '/problem-reports',
  path: '/problem-reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResidentFeedbackRoute = AdminResidentFeedbackRouteImport.update({
  id: '/resident-feedback',
  path: '/resident-feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResidentVerificationRoute =
  AdminResidentVerificationRouteImport.update({
    id: '/resident-verification',
    path: '/resident-verification',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminTransactionHistoryRoute = AdminTransactionHistoryRouteImport.update({
  id: '/transaction-history',
  path: '/transaction-history',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/my-reports': typeof MyReportsRoute
  '/my-requests': typeof MyRequestsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/request-document': typeof RequestDocumentRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/document-requests': typeof AdminDocumentRequestsRoute
  '/admin/problem-reports': typeof AdminProblemReportsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/resident-feedback': typeof AdminResidentFeedbackRoute
  '/admin/resident-verification': typeof AdminResidentVerificationRoute
  '/admin/transaction-history': typeof AdminTransactionHistoryRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/my-reports': typeof MyReportsRoute
  '/my-requests': typeof MyRequestsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/request-document': typeof RequestDocumentRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/document-requests': typeof AdminDocumentRequestsRoute
  '/admin/problem-reports': typeof AdminProblemReportsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/resident-feedback': typeof AdminResidentFeedbackRoute
  '/admin/resident-verification': typeof AdminResidentVerificationRoute
  '/admin/transaction-history': typeof AdminTransactionHistoryRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/my-reports': typeof MyReportsRoute
  '/my-requests': typeof MyRequestsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/request-document': typeof RequestDocumentRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/document-requests': typeof AdminDocumentRequestsRoute
  '/admin/problem-reports': typeof AdminProblemReportsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/resident-feedback': typeof AdminResidentFeedbackRoute
  '/admin/resident-verification': typeof AdminResidentVerificationRoute
  '/admin/transaction-history': typeof AdminTransactionHistoryRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/announcements'
    | '/dashboard'
    | '/feedback'
    | '/my-reports'
    | '/my-requests'
    | '/profile'
    | '/register'
    | '/report'
    | '/request-document'
    | '/admin/announcements'
    | '/admin/document-requests'
    | '/admin/problem-reports'
    | '/admin/profile'
    | '/admin/resident-feedback'
    | '/admin/resident-verification'
    | '/admin/transaction-history'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/dashboard'
    | '/feedback'
    | '/my-reports'
    | '/my-requests'
    | '/profile'
    | '/register'
    | '/report'
    | '/request-document'
    | '/admin/announcements'
    | '/admin/document-requests'
    | '/admin/problem-reports'
    | '/admin/profile'
    | '/admin/resident-feedback'
    | '/admin/resident-verification'
    | '/admin/transaction-history'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/announcements'
    | '/dashboard'
    | '/feedback'
    | '/my-reports'
    | '/my-requests'
    | '/profile'
    | '/register'
    | '/report'
    | '/request-document'
    | '/admin/announcements'
    | '/admin/document-requests'
    | '/admin/problem-reports'
    | '/admin/profile'
    | '/admin/resident-feedback'
    | '/admin/resident-verification'
    | '/admin/transaction-history'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRoute
  DashboardRoute: typeof DashboardRoute
  FeedbackRoute: typeof FeedbackRoute
  MyReportsRoute: typeof MyReportsRoute
  MyRequestsRoute: typeof MyRequestsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportRoute: typeof ReportRoute
  RequestDocumentRoute: typeof RequestDocumentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-reports': {
      id: '/my-reports'
      path: '/my-reports'
      fullPath: '/my-reports'
      preLoaderRoute: typeof MyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-requests': {
      id: '/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof MyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-document': {
      id: '/request-document'
      path: '/request-document'
      fullPath: '/request-document'
      preLoaderRoute: typeof RequestDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/document-requests': {
      id: '/admin/document-requests'
      path: '/document-requests'
      fullPath: '/admin/document-requests'
      preLoaderRoute: typeof AdminDocumentRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/problem-reports': {
      id: '/admin/problem-reports'
      path: '/problem-reports'
      fullPath: '/admin/problem-reports'
      preLoaderRoute: typeof AdminProblemReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resident-feedback': {
      id: '/admin/resident-feedback'
      path: '/resident-feedback'
      fullPath: '/admin/resident-feedback'
      preLoaderRoute: typeof AdminResidentFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resident-verification': {
      id: '/admin/resident-verification'
      path: '/resident-verification'
      fullPath: '/admin/resident-verification'
      preLoaderRoute: typeof AdminResidentVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transaction-history': {
      id: '/admin/transaction-history'
      path: '/transaction-history'
      fullPath: '/admin/transaction-history'
      preLoaderRoute: typeof AdminTransactionHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminDocumentRequestsRoute: typeof AdminDocumentRequestsRoute
  AdminProblemReportsRoute: typeof AdminProblemReportsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminResidentFeedbackRoute: typeof AdminResidentFeedbackRoute
  AdminResidentVerificationRoute: typeof AdminResidentVerificationRoute
  AdminTransactionHistoryRoute: typeof AdminTransactionHistoryRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminDocumentRequestsRoute: AdminDocumentRequestsRoute,
  AdminProblemReportsRoute: AdminProblemReportsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminResidentFeedbackRoute: AdminResidentFeedbackRoute,
  AdminResidentVerificationRoute: AdminResidentVerificationRoute,
  AdminTransactionHistoryRoute: AdminTransactionHistoryRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRoute,
  DashboardRoute: DashboardRoute,
  FeedbackRoute: FeedbackRoute,
  MyReportsRoute: MyReportsRoute,
  MyRequestsRoute: MyRequestsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportRoute: ReportRoute,
  RequestDocumentRoute: RequestDocumentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.jsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
